### ISSUE TITLE
Waveform amplitude displayed incorrectly

### ISSUE THREAD

**Issue by MatthewGB** [zadokstorkey/Y2-Design-Module-Group-11-PC-Side#10]
An amplitude of 2048 should be in the middle, instead the software seems to push the waveform to the top.

![image](https://user-images.githubusercontent.com/4646895/116237176-ce4bce80-a757-11eb-90d1-3a33da5c464f.png)
This waveform has a peak of 2300(/4096) yet is at the top of the screen

**Comment by zadokstorkey** [comment]
Thanks for this, I might have already fixed this when I was doing the variable scale which I haven't released yet but I'll give it a check.

**Comment by zadokstorkey** [comment]
I believe this is fixed now.
